In [27]:
#kerasのミニマムなサンプル
#https://qiita.com/Ishotihadus/items/c2f864c0cde3d17b7efb
#適当なn次元の配列を入力したら、その和が特定の値より大きいときに1と教えてくれるニューラルネットを作る

import numpy as np
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation

#5次元のデータを250個作成
data = np.random.rand(250,5)
#サンプル表示
data_sample = np.random.rand(2,5)
print('====')
print(data_sample)

#250個の各データに対して5次元の和をとり、それが2.5より大きいときに1となる（そうでないときは0となる）ような配列
#https://keras.io/ja/utils/np_utils/
labels = np_utils.to_categorical((np.sum(data, axis=1) > 2.5) * 1)
labels_sample = np_utils.to_categorical((np.sum(data_sample, axis=1) > 2.5) * 1)
print('====')
print(np.sum(data_sample, axis=1))
print('====')
print((np.sum(data_sample, axis=1) > 2.5) * 1)
print('====')
print(labels_sample)






====
[[ 0.68420741  0.76207352  0.93374116  0.24126951  0.95365417]
 [ 0.11565264  0.51002671  0.02583501  0.3522547   0.41184675]]
====
[ 3.57494577  1.41561581]
====
[1 0]
====
[[ 0.  1.]
 [ 1.  0.]]


In [10]:
#Sequentialはただ層を積み上げるだけの単純なモデル
model = Sequential([Dense(20, input_dim=5), Activation('relu'), Dense(2, activation='softmax')])
#コンパイル
model.compile('rmsprop', 'categorical_crossentropy', metrics=['accuracy'])
#学習
model.fit(data, labels, nb_epoch=300, validation_split=0.2)

test = np.random.rand(200, 5)
#予測
predict = np.argmax(model.predict(test), axis=1)
real = (np.sum(test, axis=1) > 2.5) * 1
print(sum(predict == real) / 200.0)

/anaconda3/lib/python3.6/site-packages/keras/models.py:939: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 200 samples, validate on 50 samples
Epoch 1/300
200/200 [==============================] - 0s 2ms/step - loss: 0.6792 - acc: 0.5050 - val_loss: 0.7033 - val_acc: 0.4600
Epoch 2/300
200/200 [==============================] - 0s 126us/step - loss: 0.6711 - acc: 0.5150 - val_loss: 0.6989 - val_acc: 0.4800
Epoch 3/300
200/200 [==============================] - 0s 183us/step - loss: 0.6667 - acc: 0.5450 - val_loss: 0.6931 - val_acc: 0.5200
Epoch 4/300
200/200 [==============================] - 0s 186us/step - loss: 0.6611 - acc: 0.5500 - val_loss: 0.6899 - val_acc: 0.5600
Epoch 5/300
200/200 [==============================] - 0s 244us/step - loss: 0.6584 - acc: 0.5500 - val_loss: 0.6863 - val_acc: 0.5400
Epoch 6/300
200/200 [==============================] - 0s 296us/step - loss: 0.6553 - acc: 0.5750 - val_loss: 0.6842 - val_acc: 0.5400
Epoch 7/300
200/200 [==============================] - 0s 125us/step - loss: 0.6525 - acc: 0.5900 - val_loss: 0.6815 - val_acc: 0.6000
Epoch 8/300


200/200 [==============================] - 0s 174us/step - loss: 0.4891 - acc: 0.8400 - val_loss: 0.5295 - val_acc: 0.7600
Epoch 62/300
200/200 [==============================] - 0s 102us/step - loss: 0.4851 - acc: 0.8450 - val_loss: 0.5269 - val_acc: 0.7600
Epoch 63/300
200/200 [==============================] - 0s 151us/step - loss: 0.4820 - acc: 0.8450 - val_loss: 0.5234 - val_acc: 0.7600
Epoch 64/300
200/200 [==============================] - 0s 98us/step - loss: 0.4789 - acc: 0.8450 - val_loss: 0.5177 - val_acc: 0.8200
Epoch 65/300
200/200 [==============================] - 0s 134us/step - loss: 0.4758 - acc: 0.8550 - val_loss: 0.5166 - val_acc: 0.7600
Epoch 66/300
200/200 [==============================] - 0s 152us/step - loss: 0.4720 - acc: 0.8500 - val_loss: 0.5127 - val_acc: 0.7800
Epoch 67/300
200/200 [==============================] - 0s 131us/step - loss: 0.4688 - acc: 0.8500 - val_loss: 0.5068 - val_acc: 0.8200
Epoch 68/300
200/200 [==============================] - 0s 115

200/200 [==============================] - 0s 104us/step - loss: 0.2989 - acc: 0.9500 - val_loss: 0.3270 - val_acc: 0.9400
Epoch 122/300
200/200 [==============================] - 0s 108us/step - loss: 0.2958 - acc: 0.9550 - val_loss: 0.3221 - val_acc: 0.9600
Epoch 123/300
200/200 [==============================] - 0s 95us/step - loss: 0.2936 - acc: 0.9600 - val_loss: 0.3227 - val_acc: 0.9400
Epoch 124/300
200/200 [==============================] - 0s 148us/step - loss: 0.2921 - acc: 0.9500 - val_loss: 0.3198 - val_acc: 0.9400
Epoch 125/300
200/200 [==============================] - 0s 143us/step - loss: 0.2891 - acc: 0.9600 - val_loss: 0.3146 - val_acc: 0.9600
Epoch 126/300
200/200 [==============================] - 0s 125us/step - loss: 0.2867 - acc: 0.9650 - val_loss: 0.3109 - val_acc: 0.9400
Epoch 127/300
200/200 [==============================] - 0s 134us/step - loss: 0.2843 - acc: 0.9700 - val_loss: 0.3114 - val_acc: 0.9400
Epoch 128/300
200/200 [==============================] -

Epoch 181/300
200/200 [==============================] - 0s 157us/step - loss: 0.2015 - acc: 0.9750 - val_loss: 0.2203 - val_acc: 0.9400
Epoch 182/300
200/200 [==============================] - 0s 126us/step - loss: 0.2003 - acc: 0.9750 - val_loss: 0.2188 - val_acc: 0.9400
Epoch 183/300
200/200 [==============================] - 0s 151us/step - loss: 0.1994 - acc: 0.9850 - val_loss: 0.2170 - val_acc: 0.9600
Epoch 184/300
200/200 [==============================] - 0s 145us/step - loss: 0.1979 - acc: 0.9750 - val_loss: 0.2161 - val_acc: 0.9400
Epoch 185/300
200/200 [==============================] - 0s 140us/step - loss: 0.1970 - acc: 0.9750 - val_loss: 0.2188 - val_acc: 0.9400
Epoch 186/300
200/200 [==============================] - 0s 198us/step - loss: 0.1958 - acc: 0.9800 - val_loss: 0.2146 - val_acc: 0.9600
Epoch 187/300
200/200 [==============================] - 0s 150us/step - loss: 0.1943 - acc: 0.9800 - val_loss: 0.2163 - val_acc: 0.9400
Epoch 188/300
200/200 [==================

Epoch 241/300
200/200 [==============================] - 0s 115us/step - loss: 0.1519 - acc: 0.9850 - val_loss: 0.1695 - val_acc: 0.9600
Epoch 242/300
200/200 [==============================] - 0s 144us/step - loss: 0.1517 - acc: 0.9850 - val_loss: 0.1680 - val_acc: 0.9600
Epoch 243/300
200/200 [==============================] - 0s 132us/step - loss: 0.1504 - acc: 0.9800 - val_loss: 0.1674 - val_acc: 0.9600
Epoch 244/300
200/200 [==============================] - 0s 162us/step - loss: 0.1512 - acc: 0.9800 - val_loss: 0.1677 - val_acc: 0.9600
Epoch 245/300
200/200 [==============================] - 0s 160us/step - loss: 0.1489 - acc: 0.9850 - val_loss: 0.1674 - val_acc: 0.9600
Epoch 246/300
200/200 [==============================] - 0s 164us/step - loss: 0.1485 - acc: 0.9800 - val_loss: 0.1678 - val_acc: 0.9400
Epoch 247/300
200/200 [==============================] - 0s 174us/step - loss: 0.1476 - acc: 0.9850 - val_loss: 0.1650 - val_acc: 0.9600
Epoch 248/300
200/200 [==================

200/200 [==============================] - 0s 107us/step - loss: 0.1227 - acc: 0.9850 - val_loss: 0.1389 - val_acc: 0.9400
0.945
