In [70]:
# Pandas と Numpy を読み込み
import pandas as pd
import numpy as np


In [71]:
#Series (1 次元の値のリスト) を作成する
s = pd.Series([1,3,5,np.nan,6,8])
print("====")
print(s)


====
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [72]:
dates = pd.date_range('20130101', periods=6)
print("====")
print(dates)


====
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [73]:
#データフレームの作成
#A～Fの各列に数値、文字列、日付、Numpy の行列などを格納
df = pd.DataFrame({ 'A' : 1.,
                        'B' : pd.Timestamp('20130102'),
                        'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                        'D' : np.array([3] * 4,dtype='int32'),
                        'E' : pd.Categorical(["test","train","test","train"]),
                        'F' : 'foo' })

print("====")
print(df)# 日付の Series を作成
print("====")
print(df.dtypes)#各列の型を確認
print("====")
print(df.shape)#行列サイズを確認
print("====")
print(df.T)#行列を入れ替えた転置行列を表示


====
     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
====
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
====
(4, 6)
====
                     0                    1                    2  \
A                    1                    1                    1   
B  2013-01-02 00:00:00  2013-01-02 00:00:00  2013-01-02 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                    1  
B  2013-01-02 00:00:00  
C                    1  
D                    3  
E                train  
F                  foo

In [74]:
#Numpy の 行列からデータフレームを作成する
# 6 x 4 の 2 次元の行列からデータフレームを作成し、各列に A, B, C, D という名前を付与
matrix = np.random.randn(6,4)
print("====")
print(matrix)

df2 = pd.DataFrame(matrix, columns=list('ABCD'))
print("====")
print(df2)
#基本統計量を算出する
#件数 (count)、平均値 (mean)、標準偏差 (std)、最小値(min)、第一四分位数 (25%)、中央値 (50%)、第三四分位数 (75%)、最大値 (max) を確認できる
df2_desc = df2.describe()
print("====")
print(df2_desc)
# 行名でソート
print("====行名でソート")
print(df2.sort_index(ascending=False))

# 列名でソート
print("====列名でソート")
print(df2.sort_index(axis=1, ascending=False))

# B 列の値の小さい順 (昇順) にソート
print("====B 列の値の小さい順 (昇順) にソート")
print(df2.sort_values(by='B'))

# C 列の値の大きい順 (降順) にソート
print("====C 列の値の大きい順 (降順) にソート")
print(df2.sort_values(by='C', ascending=False))



====
[[ 1.26260454  0.35869363 -0.25584429 -0.38175163]
 [ 0.7604221  -0.70911745  0.57765255 -1.04542761]
 [-0.26853378  0.37000191  0.66625417  0.11874918]
 [-0.2799615  -0.26880818 -1.61838739  0.85591199]
 [-0.89683614 -1.92588555  0.02506647  0.17684585]
 [ 0.36776721 -0.04586155 -1.17873798  0.86313381]]
====
          A         B         C         D
0  1.262605  0.358694 -0.255844 -0.381752
1  0.760422 -0.709117  0.577653 -1.045428
2 -0.268534  0.370002  0.666254  0.118749
3 -0.279961 -0.268808 -1.618387  0.855912
4 -0.896836 -1.925886  0.025066  0.176846
5  0.367767 -0.045862 -1.178738  0.863134
====
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.157577 -0.370163 -0.297333  0.097910
std    0.789112  0.863676  0.929712  0.735404
min   -0.896836 -1.925886 -1.618387 -1.045428
25%   -0.277105 -0.599040 -0.948015 -0.256626
50%    0.049617 -0.157335 -0.115389  0.147798
75%    0.662258  0.257555  0.439506  0.686145
max    1.262605 

In [75]:
#辞書(ディクショナリ)からデータフレームを作成する
a_values = [1, 2, 3, 4, 5]
b_values = np.random.rand(5)
c_values = ["apple", "banana", "strawberry", "peach", "orange"]
my_dict = {"colA": a_values, "colB": b_values, "colC":c_values}
my_df = pd.DataFrame.from_dict(my_dict)
print("====")
print(my_df)
#行名を表示
print("====")
print(my_df.index)
#行数を表示
print("====")
print(len(my_df.index))

#列名を表示
print("====")
print(my_df.columns)
#列数を表示
print("====")
print(len(my_df.columns))

#値のみを 2 次元行列として表示する
print("====")
print(my_df.values)
#特定の列を取得する
print("====")
print(my_df.colA)
print(my_df["colA"])

====
   colA      colB        colC
0     1  0.939168       apple
1     2  0.240166      banana
2     3  0.773911  strawberry
3     4  0.687378       peach
4     5  0.222150      orange
====
RangeIndex(start=0, stop=5, step=1)
====
5
====
Index(['colA', 'colB', 'colC'], dtype='object')
====
3
====
[[1 0.9391677947713448 'apple']
 [2 0.2401658292574136 'banana']
 [3 0.773911307118199 'strawberry']
 [4 0.6873776948399924 'peach']
 [5 0.22214993009504702 'orange']]
====
0    1
1    2
2    3
3    4
4    5
Name: colA, dtype: int64
0    1
1    2
2    3
3    4
4    5
Name: colA, dtype: int64


In [76]:
# 先頭 3 行を抽出
my_df.head(3)

colA      colB        colC
0     1  0.939168       apple
1     2  0.240166      banana
2     3  0.773911  strawberry

In [77]:
# 末尾2行を抽出
my_df.tail(2)

colA      colB    colC
3     4  0.687378   peach
4     5  0.222150  orange

In [78]:
#先頭から 3 行目までを抽出
print(my_df[:3])

   colA      colB        colC
0     1  0.939168       apple
1     2  0.240166      banana
2     3  0.773911  strawberry


In [79]:
# 2行目から 4行目までを抽出。1行目は0から指定。
print(my_df[1:4])

   colA      colB        colC
1     2  0.240166      banana
2     3  0.773911  strawberry
3     4  0.687378       peach


In [80]:
# 2行目から 4行目、かつ、 "colA" 列と "colC" 列を取得
print(my_df.loc[1:4,['colA','colC']])

   colA        colC
1     2      banana
2     3  strawberry
3     4       peach
4     5      orange


In [85]:
# 先頭から2行、かつ、 1列と 3列を取得
print(my_df.iloc[:2,[0,2]])

   colA    colC
0     1   apple
1     2  banana
